// ACAS Resolution Advisory Report
// Definition: Currently active Resolution Advisory (RA), if any, generated by the
// ACAS associated with the transponder transmitting the RA
// message and threat identity data.
// Format: Seven-octet fixed length Data Item.

import { int8Toint16, int8Toint32, mask, maskAndShift } from "../utils/bitUtils.js";

import { pushDataItem } from "../decoder";

const name = "ACAS_resolution_advisory_report";
const byteLength = 8;
export function parse(record) {

    let ARA = int8Toint16(record[1], record[2])
    let RAC = int8Toint16(record[2], record[3])
    let TID = int8Toint32(record[3], record[4], record[5], record[6])


    pushDataItem(name, {
        TYP: maskAndShift(record[0], 8, 4),
        STYP: maskAndShift(record[0], 3, 1),
        ARA: maskAndShift(ARA, 16, 3),
        RAC: maskAndShift(RAC, 10, 7),
        RAT: maskAndShift(record[3], 6),
        MTE: maskAndShift(record[3], 5),
        TTI: maskAndShift(record[3], 4, 3),
        TID: maskAndShift(TID, 26, 1),
    });

    return record.subarray(byteLength);
}